import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "../styles/globals.css";

const ember = localFont({
    variable: "--ember",
    display: "swap",
    src: [
        {
            path: "../../public/fonts/AmazonEmber_Lt.ttf",
            weight: "300",
            style: "light",
        },
        {
            path: "../../public/fonts/AmazonEmber_Rg.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/Amazon-Ember-Medium.ttf",
            weight: "500",
            style: "medium",
        },
        {
            path: "../../public/fonts/AmazonEmber_Bd.ttf",
            weight: "700",
            style: "bold",
        },
        {
            path: "../../public/fonts/AmazonEmber_He.ttf",
            weight: "800",
            style: "heavy",
        },
    ],
});

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    "bg-background antialiased min-h-screen text-foreground",
                    ember.className
                )}
            >
                {children}
                <Toaster position="top-right" />
            </body>
        </html>
    );
}
